{
  "name": "mbpp_637_noprofit_noloss",
  "language": "php",
  "prompt": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n",
  "doctests": "keep",
  "original": "/home/arjun/repos/MultiPL-E/datasets/../datasets/mbpp-typed/mbpp_637_noprofit_noloss.py",
  "prompt_terminology": "verbatim",
  "tests": "function candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
  "stop_tokens": [
    "\nfunction",
    "\n?>",
    "\n//",
    "\n#"
  ],
  "results": [
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } else if ($actual_cost < $sale_amount) {\n        echo \"Profit\";\n    } else {\n        echo \"Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp5zhmej7t.php:18\nStack trace:\n#0 /tmp/tmp5zhmej7t.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp5zhmej7t.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n\tif ($actual_cost == $sale_amount) {\n\t\techo \"No profit and no loss\";\n\t} else {\n\t\techo \"Profit or loss\";\n\t}\n}\n\nnoprofit_noloss(100, 100);\necho \"<br>\";\nnoprofit_noloss(100, 200);\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "No profit and no loss<br>Profit or lossProfit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpottzbdyx.php:19\nStack trace:\n#0 /tmp/tmpottzbdyx.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpottzbdyx.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } else if ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpna87wtfa.php:18\nStack trace:\n#0 /tmp/tmpna87wtfa.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpna87wtfa.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    }\n    elseif($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    }\n    else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpktp9b_8_.php:20\nStack trace:\n#0 /tmp/tmpktp9b_8_.php(25): test()\n#1 {main}\n  thrown in /tmp/tmpktp9b_8_.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } elseif ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\nnoprofit_noloss(1000, 2000);\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "ProfitLoss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp5kn2vwfu.php:18\nStack trace:\n#0 /tmp/tmp5kn2vwfu.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp5kn2vwfu.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        return true;\n    }\n    return false;\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    } elseif ($actual_cost < $sale_amount) {\n        echo \"Profit\";\n    } else {\n        echo \"Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmphbxouuwx.php:18\nStack trace:\n#0 /tmp/tmphbxouuwx.php(23): test()\n#1 {main}\n  thrown in /tmp/tmphbxouuwx.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } elseif ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nnoprofit_noloss(100, 100);\necho \"<br>\";\nnoprofit_noloss(100, 50);\necho \"<br>\";\nnoprofit_noloss(100, 150);\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "No profit no loss<br>Loss<br>ProfitLoss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp7pic3ynz.php:23\nStack trace:\n#0 /tmp/tmp7pic3ynz.php(28): test()\n#1 {main}\n  thrown in /tmp/tmp7pic3ynz.php on line 23\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    } else if ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp5adu5c25.php:18\nStack trace:\n#0 /tmp/tmp5adu5c25.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp5adu5c25.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    }\n    else {\n        echo \"Profit or loss\";\n    }\n}\nnoprofit_noloss(1000, 1000);\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "No profit and no lossProfit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpvihrxawz.php:17\nStack trace:\n#0 /tmp/tmpvihrxawz.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpvihrxawz.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    }\n    elseif($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    }\n    else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpuq4p6b79.php:20\nStack trace:\n#0 /tmp/tmpuq4p6b79.php(25): test()\n#1 {main}\n  thrown in /tmp/tmpuq4p6b79.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    }\n    else if($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    }\n    else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpwehn0tv6.php:20\nStack trace:\n#0 /tmp/tmpwehn0tv6.php(25): test()\n#1 {main}\n  thrown in /tmp/tmpwehn0tv6.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } else if ($actual_cost < $sale_amount) {\n        echo \"Profit\";\n    } else {\n        echo \"Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp5zhmej7t.php:18\nStack trace:\n#0 /tmp/tmp5zhmej7t.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp5zhmej7t.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    } else if ($actual_cost < $sale_amount) {\n        echo \"Profit\";\n    } else {\n        echo \"Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpyej_8yb3.php:18\nStack trace:\n#0 /tmp/tmpyej_8yb3.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpyej_8yb3.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } else if ($actual_cost < $sale_amount) {\n        echo \"Profit\";\n    } else {\n        echo \"Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp5zhmej7t.php:18\nStack trace:\n#0 /tmp/tmp5zhmej7t.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp5zhmej7t.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    } else {\n        echo \"Profit or loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpousfa8wn.php:16\nStack trace:\n#0 /tmp/tmpousfa8wn.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpousfa8wn.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        return true;\n    }\n    return false;\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    } else {\n        echo \"Profit or Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "Profit or Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpv859e1_2.php:16\nStack trace:\n#0 /tmp/tmpv859e1_2.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpv859e1_2.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    }\n    elseif ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    }\n    else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp27my7i7y.php:20\nStack trace:\n#0 /tmp/tmp27my7i7y.php(25): test()\n#1 {main}\n  thrown in /tmp/tmp27my7i7y.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n\tif($actual_cost == $sale_amount) {\n\t\techo \"No profit no loss\";\n\t} else {\n\t\techo \"Profit or loss\";\n\t}\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpztghhh7t.php:16\nStack trace:\n#0 /tmp/tmpztghhh7t.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpztghhh7t.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } elseif ($actual_cost < $sale_amount) {\n        echo \"Profit\";\n    } else {\n        echo \"Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp3ssaapsk.php:18\nStack trace:\n#0 /tmp/tmp3ssaapsk.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp3ssaapsk.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit, No loss\";\n    } else if ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123509,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpa0nyo_2r.php:18\nStack trace:\n#0 /tmp/tmpa0nyo_2r.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpa0nyo_2r.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n\tif($actual_cost == $sale_amount) {\n\t\techo \"No Profit No Loss\";\n\t}\n\telseif($actual_cost > $sale_amount) {\n\t\techo \"Loss\";\n\t}\n\telse {\n\t\techo \"Profit\";\n\t}\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpbg8dxvkn.php:20\nStack trace:\n#0 /tmp/tmpbg8dxvkn.php(25): test()\n#1 {main}\n  thrown in /tmp/tmpbg8dxvkn.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } elseif($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp0qnhscww.php:18\nStack trace:\n#0 /tmp/tmp0qnhscww.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp0qnhscww.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    } else {\n        echo \"Profit or loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpousfa8wn.php:16\nStack trace:\n#0 /tmp/tmpousfa8wn.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpousfa8wn.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n\tif ($actual_cost == $sale_amount) {\n\t\treturn true;\n\t} else {\n\t\treturn false;\n\t}\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"There is no profit and no loss\";\n    } else {\n        echo \"There is profit or loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123509,
      "stdout": "There is profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpy4zmbikj.php:16\nStack trace:\n#0 /tmp/tmpy4zmbikj.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpy4zmbikj.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    } elseif ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123509,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpmj6qq7wm.php:18\nStack trace:\n#0 /tmp/tmpmj6qq7wm.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpmj6qq7wm.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } else if ($actual_cost < $sale_amount) {\n        echo \"Profit\";\n    } else {\n        echo \"Loss\";\n    }\n}\n\nnoprofit_noloss(100, 100);\necho \"<br>\";\nnoprofit_noloss(100, 200);\necho \"<br>\";\nnoprofit_noloss(100, 50);\necho \"<br>\";\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "No profit no loss<br>Profit<br>Loss<br>Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmprrkcp8wm.php:24\nStack trace:\n#0 /tmp/tmprrkcp8wm.php(29): test()\n#1 {main}\n  thrown in /tmp/tmprrkcp8wm.php on line 24\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    }\n    else {\n        echo \"Profit or loss\";\n    }\n}\n\nnoprofit_noloss(100, 100);\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "No profit no lossProfit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpapwg5k9y.php:18\nStack trace:\n#0 /tmp/tmpapwg5k9y.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpapwg5k9y.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    } else {\n        echo \"Profit or Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "Profit or Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpv859e1_2.php:16\nStack trace:\n#0 /tmp/tmpv859e1_2.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpv859e1_2.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } else if ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpna87wtfa.php:18\nStack trace:\n#0 /tmp/tmpna87wtfa.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpna87wtfa.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    } else if ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nnoprofit_noloss(100, 100);\necho \"<br>\";\nnoprofit_noloss(100, 200);\necho \"<br>\";\nnoprofit_noloss(200, 100);\necho \"<br>\";\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "No Profit No Loss<br>Profit<br>Loss<br>Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpsask3qwr.php:25\nStack trace:\n#0 /tmp/tmpsask3qwr.php(30): test()\n#1 {main}\n  thrown in /tmp/tmpsask3qwr.php on line 25\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } elseif ($actual_cost < $sale_amount) {\n        echo \"Profit\";\n    } else {\n        echo \"Loss\";\n    }\n}\n\nnoprofit_noloss(100, 200);\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "ProfitLoss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpe79d9c_2.php:19\nStack trace:\n#0 /tmp/tmpe79d9c_2.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpe79d9c_2.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    }\n    elseif($actual_cost < $sale_amount) {\n        echo \"Profit\";\n    }\n    else {\n        echo \"Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp8rpxyio1.php:20\nStack trace:\n#0 /tmp/tmp8rpxyio1.php(25): test()\n#1 {main}\n  thrown in /tmp/tmp8rpxyio1.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    }\n    return false;\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123509,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } else {\n        echo \"Profit or loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123509,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxhaaqc47.php:16\nStack trace:\n#0 /tmp/tmpxhaaqc47.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpxhaaqc47.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    } else if ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp5adu5c25.php:18\nStack trace:\n#0 /tmp/tmp5adu5c25.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp5adu5c25.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } elseif ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxwx_8k6i.php:18\nStack trace:\n#0 /tmp/tmpxwx_8k6i.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpxwx_8k6i.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit, No loss\";\n    } elseif ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmplkafftjo.php:18\nStack trace:\n#0 /tmp/tmplkafftjo.php(23): test()\n#1 {main}\n  thrown in /tmp/tmplkafftjo.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    } elseif ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } elseif ($actual_cost < $sale_amount) {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmplf3cy8d0.php:18\nStack trace:\n#0 /tmp/tmplf3cy8d0.php(23): test()\n#1 {main}\n  thrown in /tmp/tmplf3cy8d0.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    } else if($actual_cost < $sale_amount) {\n        echo \"Profit\";\n    } else {\n        echo \"Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpgda_ur5_.php:18\nStack trace:\n#0 /tmp/tmpgda_ur5_.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpgda_ur5_.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    }\n    else {\n        echo \"Profit or Loss\";\n    }\n}\nnoprofit_noloss(100, 100);\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "No Profit No LossProfit or Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmposc28idr.php:17\nStack trace:\n#0 /tmp/tmposc28idr.php(22): test()\n#1 {main}\n  thrown in /tmp/tmposc28idr.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit, no loss\";\n    } else {\n        echo \"Profit or loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp2mr3w71z.php:16\nStack trace:\n#0 /tmp/tmp2mr3w71z.php(21): test()\n#1 {main}\n  thrown in /tmp/tmp2mr3w71z.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    } elseif ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123509,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp0qbfdmyo.php:18\nStack trace:\n#0 /tmp/tmp0qbfdmyo.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp0qbfdmyo.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit, no loss\";\n    } else if ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nnoprofit_noloss(100, 100);\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "No profit, no lossLoss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp8dz17667.php:19\nStack trace:\n#0 /tmp/tmp8dz17667.php(24): test()\n#1 {main}\n  thrown in /tmp/tmp8dz17667.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    } else if ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nnoprofit_noloss(100, 100);\necho \"\\n\";\nnoprofit_noloss(100, 200);\necho \"\\n\";\nnoprofit_noloss(100, 50);\necho \"\\n\";\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "No Profit No Loss\nProfit\nLoss\nLoss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp5ibu9w10.php:25\nStack trace:\n#0 /tmp/tmp5ibu9w10.php(30): test()\n#1 {main}\n  thrown in /tmp/tmp5ibu9w10.php on line 25\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n\tif($actual_cost == $sale_amount) {\n\t\techo \"No profit no loss\";\n\t}\n\telse {\n\t\techo \"Profit or loss\";\n\t}\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmphscui9i8.php:17\nStack trace:\n#0 /tmp/tmphscui9i8.php(22): test()\n#1 {main}\n  thrown in /tmp/tmphscui9i8.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n\tif($actual_cost == $sale_amount) {\n\t\treturn true;\n\t} else {\n\t\treturn false;\n\t}\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"There is no profit and no loss\";\n    }\n}\nnoprofit_noloss(1000, 1000);\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "There is no profit and no loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpnwqa3vyf.php:14\nStack trace:\n#0 /tmp/tmpnwqa3vyf.php(19): test()\n#1 {main}\n  thrown in /tmp/tmpnwqa3vyf.php on line 14\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } elseif ($actual_cost < $sale_amount) {\n        echo \"Profit\";\n    } else {\n        echo \"Loss\";\n    }\n}\n\nnoprofit_noloss(100, 100);\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "No profit no lossLoss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpfkv2a97z.php:20\nStack trace:\n#0 /tmp/tmpfkv2a97z.php(25): test()\n#1 {main}\n  thrown in /tmp/tmpfkv2a97z.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit, No loss\";\n    } else {\n        echo \"Profit or Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Profit or Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmps73pajwm.php:16\nStack trace:\n#0 /tmp/tmps73pajwm.php(21): test()\n#1 {main}\n  thrown in /tmp/tmps73pajwm.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    }\n    else {\n        echo \"Profit or loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123509,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpdjzgxw2f.php:17\nStack trace:\n#0 /tmp/tmpdjzgxw2f.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpdjzgxw2f.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } else if ($actual_cost < $sale_amount) {\n        echo \"Profit\";\n    } else {\n        echo \"Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp5zhmej7t.php:18\nStack trace:\n#0 /tmp/tmp5zhmej7t.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp5zhmej7t.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit, no loss\";\n    }\n    elseif ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    }\n    else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpcq1fkzac.php:20\nStack trace:\n#0 /tmp/tmpcq1fkzac.php(25): test()\n#1 {main}\n  thrown in /tmp/tmpcq1fkzac.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    } else if ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nnoprofit_noloss(100, 100);\necho \"<br>\";\nnoprofit_noloss(100, 50);\necho \"<br>\";\nnoprofit_noloss(50, 100);\necho \"<br>\";\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "No Profit No Loss<br>Loss<br>Profit<br>Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp0f4jv4uo.php:25\nStack trace:\n#0 /tmp/tmp0f4jv4uo.php(30): test()\n#1 {main}\n  thrown in /tmp/tmp0f4jv4uo.php on line 25\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } elseif ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxwx_8k6i.php:18\nStack trace:\n#0 /tmp/tmpxwx_8k6i.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpxwx_8k6i.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    } else {\n        echo \"Profit or loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpousfa8wn.php:16\nStack trace:\n#0 /tmp/tmpousfa8wn.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpousfa8wn.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    } elseif ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nnoprofit_noloss(100, 100);\necho \"\\n\";\nnoprofit_noloss(100, 200);\necho \"\\n\";\nnoprofit_noloss(100, 50);\necho \"\\n\";\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "No profit and no loss\nProfit\nLoss\nLoss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpsel0e1kc.php:24\nStack trace:\n#0 /tmp/tmpsel0e1kc.php(29): test()\n#1 {main}\n  thrown in /tmp/tmpsel0e1kc.php on line 24\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } elseif ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxwx_8k6i.php:18\nStack trace:\n#0 /tmp/tmpxwx_8k6i.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpxwx_8k6i.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit, no loss\";\n    } elseif ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp_lqn7wq8.php:18\nStack trace:\n#0 /tmp/tmp_lqn7wq8.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp_lqn7wq8.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    }\n    else {\n        echo \"Profit or loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpn8ddu51x.php:17\nStack trace:\n#0 /tmp/tmpn8ddu51x.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpn8ddu51x.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    } elseif ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nnoprofit_noloss(100, 100);\necho \"<br>\";\nnoprofit_noloss(100, 200);\necho \"<br>\";\nnoprofit_noloss(100, 50);\necho \"<br>\";\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "No profit and no loss<br>Profit<br>Loss<br>Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxc32ampx.php:25\nStack trace:\n#0 /tmp/tmpxc32ampx.php(30): test()\n#1 {main}\n  thrown in /tmp/tmpxc32ampx.php on line 25\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n\tif($actual_cost == $sale_amount) {\n\t\techo \"No Profit No Loss\";\n\t}\n\telse {\n\t\techo \"Profit or Loss\";\n\t}\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Profit or Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpmel8uxor.php:17\nStack trace:\n#0 /tmp/tmpmel8uxor.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpmel8uxor.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    } else if ($actual_cost < $sale_amount) {\n        echo \"Profit\";\n    } else {\n        echo \"Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpyej_8yb3.php:18\nStack trace:\n#0 /tmp/tmpyej_8yb3.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpyej_8yb3.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } elseif ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxwx_8k6i.php:18\nStack trace:\n#0 /tmp/tmpxwx_8k6i.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpxwx_8k6i.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    } elseif ($actual_cost < $sale_amount) {\n        echo \"Profit\";\n    } else {\n        echo \"Loss\";\n    }\n}\n\nnoprofit_noloss(100, 100);\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123509,
      "stdout": "No profit and no lossLoss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpi78z4rrx.php:19\nStack trace:\n#0 /tmp/tmpi78z4rrx.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpi78z4rrx.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    } else if ($actual_cost < $sale_amount) {\n        echo \"Profit\";\n    } else {\n        echo \"Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpyej_8yb3.php:18\nStack trace:\n#0 /tmp/tmpyej_8yb3.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpyej_8yb3.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123509,
      "stdout": "\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp_jwvkcw3.php:14\nStack trace:\n#0 /tmp/tmp_jwvkcw3.php(19): test()\n#1 {main}\n  thrown in /tmp/tmp_jwvkcw3.php on line 14\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    } else {\n        echo \"Profit or Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Profit or Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp36hw23ga.php:16\nStack trace:\n#0 /tmp/tmp36hw23ga.php(21): test()\n#1 {main}\n  thrown in /tmp/tmp36hw23ga.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    } else if ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp5adu5c25.php:18\nStack trace:\n#0 /tmp/tmp5adu5c25.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp5adu5c25.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n\tif($actual_cost == $sale_amount) {\n\t\techo \"No Profit No Loss\";\n\t}\n\telseif($actual_cost > $sale_amount) {\n\t\techo \"Loss\";\n\t}\n\telse {\n\t\techo \"Profit\";\n\t}\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpbg8dxvkn.php:20\nStack trace:\n#0 /tmp/tmpbg8dxvkn.php(25): test()\n#1 {main}\n  thrown in /tmp/tmpbg8dxvkn.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    }\n    return false;\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123509,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    }\n    else {\n        echo \"Profit or loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpoudd94_b.php:17\nStack trace:\n#0 /tmp/tmpoudd94_b.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpoudd94_b.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        return true;\n    }\n    return false;\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n\tif ($actual_cost == $sale_amount) {\n\t\techo \"No profit no loss\";\n\t} elseif ($actual_cost < $sale_amount) {\n\t\techo \"Profit\";\n\t} else {\n\t\techo \"Loss\";\n\t}\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpd7g991od.php:18\nStack trace:\n#0 /tmp/tmpd7g991od.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpd7g991od.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } else if ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nnoprofit_noloss(100, 100);\nnoprofit_noloss(100, 200);\nnoprofit_noloss(200, 100);\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "No profit no lossProfitLossLoss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp6h_0c4d8.php:21\nStack trace:\n#0 /tmp/tmp6h_0c4d8.php(26): test()\n#1 {main}\n  thrown in /tmp/tmp6h_0c4d8.php on line 21\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n\tif ($actual_cost == $sale_amount) {\n\t\techo \"No profit no loss\";\n\t} else if ($actual_cost < $sale_amount) {\n\t\techo \"Profit\";\n\t} else {\n\t\techo \"Loss\";\n\t}\n}\n\nnoprofit_noloss(100, 100);\necho \"<br>\";\nnoprofit_noloss(100, 200);\necho \"<br>\";\nnoprofit_noloss(100, 50);\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "No profit no loss<br>Profit<br>LossLoss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp07lr9v96.php:23\nStack trace:\n#0 /tmp/tmp07lr9v96.php(28): test()\n#1 {main}\n  thrown in /tmp/tmp07lr9v96.php on line 23\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } elseif ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxwx_8k6i.php:18\nStack trace:\n#0 /tmp/tmpxwx_8k6i.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpxwx_8k6i.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        return true;\n    }\n    return false;\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n\tif ($actual_cost == $sale_amount) {\n\t\techo \"No Profit No Loss\";\n\t} else {\n\t\techo \"Profit or Loss\";\n\t}\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Profit or Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpw67d1177.php:16\nStack trace:\n#0 /tmp/tmpw67d1177.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpw67d1177.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } else {\n        echo \"Profit or loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpneaxioe4.php:16\nStack trace:\n#0 /tmp/tmpneaxioe4.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpneaxioe4.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } else {\n        echo \"Profit or loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123509,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxhaaqc47.php:16\nStack trace:\n#0 /tmp/tmpxhaaqc47.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpxhaaqc47.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    } else if ($actual_cost < $sale_amount) {\n        echo \"Profit\";\n    } else {\n        echo \"Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpyej_8yb3.php:18\nStack trace:\n#0 /tmp/tmpyej_8yb3.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpyej_8yb3.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    } else if ($actual_cost < $sale_amount) {\n        echo \"Profit\";\n    } else {\n        echo \"Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpyej_8yb3.php:18\nStack trace:\n#0 /tmp/tmpyej_8yb3.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpyej_8yb3.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } else if ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpna87wtfa.php:18\nStack trace:\n#0 /tmp/tmpna87wtfa.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpna87wtfa.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    } else {\n        echo \"Profit or loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpousfa8wn.php:16\nStack trace:\n#0 /tmp/tmpousfa8wn.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpousfa8wn.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit, no loss\";\n    } else {\n        echo \"Profit or loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp2mr3w71z.php:16\nStack trace:\n#0 /tmp/tmp2mr3w71z.php(21): test()\n#1 {main}\n  thrown in /tmp/tmp2mr3w71z.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit No loss\";\n    } else if ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nnoprofit_noloss(100, 200);\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "ProfitLoss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpvr7afyvo.php:19\nStack trace:\n#0 /tmp/tmpvr7afyvo.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpvr7afyvo.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    $profit = $sale_amount - $actual_cost;\n    if($profit == 0) {\n        echo \"No profit and no loss\";\n    } else {\n        echo \"Profit or loss\";\n    }\n}\n\nnoprofit_noloss(1000, 1000);\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "No profit and no lossProfit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpldnf9ydq.php:18\nStack trace:\n#0 /tmp/tmpldnf9ydq.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpldnf9ydq.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpjly9esx0.php:14\nStack trace:\n#0 /tmp/tmpjly9esx0.php(19): test()\n#1 {main}\n  thrown in /tmp/tmpjly9esx0.php on line 14\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    } else {\n        echo \"Profit or Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "Profit or Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpv859e1_2.php:16\nStack trace:\n#0 /tmp/tmpv859e1_2.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpv859e1_2.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    }\n    elseif ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    }\n    else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpa_ju4zbm.php:20\nStack trace:\n#0 /tmp/tmpa_ju4zbm.php(25): test()\n#1 {main}\n  thrown in /tmp/tmpa_ju4zbm.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    } else {\n        echo \"Profit or Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "Profit or Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpv859e1_2.php:16\nStack trace:\n#0 /tmp/tmpv859e1_2.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpv859e1_2.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    } elseif ($actual_cost < $sale_amount) {\n        echo \"Profit\";\n    } else {\n        echo \"Loss\";\n    }\n}\n\nnoprofit_noloss(100, 100);\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "No Profit No LossLoss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmphcn5s9zt.php:19\nStack trace:\n#0 /tmp/tmphcn5s9zt.php(24): test()\n#1 {main}\n  thrown in /tmp/tmphcn5s9zt.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    } else {\n        echo \"Profit or Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "Profit or Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpv859e1_2.php:16\nStack trace:\n#0 /tmp/tmpv859e1_2.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpv859e1_2.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        return true;\n    }\n    return false;\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n  if ($actual_cost == $sale_amount) {\n    echo \"No profit no loss\";\n  }\n  elseif ($actual_cost > $sale_amount) {\n    echo \"Loss\";\n  }\n  else {\n    echo \"Profit\";\n  }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmporimqizb.php:20\nStack trace:\n#0 /tmp/tmporimqizb.php(25): test()\n#1 {main}\n  thrown in /tmp/tmporimqizb.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } else if ($actual_cost < $sale_amount) {\n        echo \"Profit\";\n    } else {\n        echo \"Loss\";\n    }\n}\n\nnoprofit_noloss(100, 100);\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "No profit no lossLoss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpz8g5jcoi.php:19\nStack trace:\n#0 /tmp/tmpz8g5jcoi.php(24): test()\n#1 {main}\n  thrown in /tmp/tmpz8g5jcoi.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n\tif ($actual_cost == $sale_amount) {\n\t\techo \"No profit no loss\";\n\t} elseif ($actual_cost < $sale_amount) {\n\t\techo \"Profit\";\n\t} else {\n\t\techo \"Loss\";\n\t}\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpd7g991od.php:18\nStack trace:\n#0 /tmp/tmpd7g991od.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpd7g991od.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    } else if ($actual_cost < $sale_amount) {\n        echo \"Profit\";\n    } else {\n        echo \"Loss\";\n    }\n}\n\nnoprofit_noloss(100, 200);\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123509,
      "stdout": "ProfitLoss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp3ud4dfw2.php:19\nStack trace:\n#0 /tmp/tmp3ud4dfw2.php(24): test()\n#1 {main}\n  thrown in /tmp/tmp3ud4dfw2.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } elseif ($actual_cost < $sale_amount) {\n        echo \"Profit\";\n    } else {\n        echo \"Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp3ssaapsk.php:18\nStack trace:\n#0 /tmp/tmp3ssaapsk.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp3ssaapsk.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    } else {\n        echo \"Profit or loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpousfa8wn.php:16\nStack trace:\n#0 /tmp/tmpousfa8wn.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpousfa8wn.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    } elseif ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123509,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpmj6qq7wm.php:18\nStack trace:\n#0 /tmp/tmpmj6qq7wm.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpmj6qq7wm.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n\tif($actual_cost == $sale_amount) {\n\t\techo \"No Profit No Loss\";\n\t}\n\telse {\n\t\techo \"Profit or Loss\";\n\t}\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Profit or Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpmel8uxor.php:17\nStack trace:\n#0 /tmp/tmpmel8uxor.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpmel8uxor.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    } elseif ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nnoprofit_noloss(100, 100);\necho \"<br>\";\nnoprofit_noloss(100, 200);\necho \"<br>\";\nnoprofit_noloss(200, 100);\necho \"<br>\";\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "No Profit No Loss<br>Profit<br>Loss<br>Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp47gya972.php:25\nStack trace:\n#0 /tmp/tmp47gya972.php(30): test()\n#1 {main}\n  thrown in /tmp/tmp47gya972.php on line 25\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n\tif($actual_cost == $sale_amount) {\n\t\techo \"No profit and no loss\";\n\t}\n\telse {\n\t\techo \"Profit or loss\";\n\t}\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpngjnk9rc.php:17\nStack trace:\n#0 /tmp/tmpngjnk9rc.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpngjnk9rc.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    } else if ($actual_cost < $sale_amount) {\n        echo \"Profit\";\n    } else {\n        echo \"Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpyej_8yb3.php:18\nStack trace:\n#0 /tmp/tmpyej_8yb3.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpyej_8yb3.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } else if ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nnoprofit_noloss(100, 100);\necho \"\\n\";\nnoprofit_noloss(100, 200);\necho \"\\n\";\nnoprofit_noloss(100, 50);\necho \"\\n\";\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "No profit no loss\nProfit\nLoss\nLoss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpqyhj6tbj.php:25\nStack trace:\n#0 /tmp/tmpqyhj6tbj.php(30): test()\n#1 {main}\n  thrown in /tmp/tmpqyhj6tbj.php on line 25\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    } else {\n        echo \"Profit or loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpousfa8wn.php:16\nStack trace:\n#0 /tmp/tmpousfa8wn.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpousfa8wn.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } else {\n        echo \"Profit or Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Profit or Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpoacqfq7h.php:16\nStack trace:\n#0 /tmp/tmpoacqfq7h.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpoacqfq7h.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n\tif($actual_cost == $sale_amount) {\n\t\techo \"No profit and no loss\";\n\t} else {\n\t\techo \"Profit or loss\";\n\t}\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123509,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp3uayfm1p.php:16\nStack trace:\n#0 /tmp/tmp3uayfm1p.php(21): test()\n#1 {main}\n  thrown in /tmp/tmp3uayfm1p.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    }\n    else {\n        echo \"Profit or loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpn8ddu51x.php:17\nStack trace:\n#0 /tmp/tmpn8ddu51x.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpn8ddu51x.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } elseif ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nnoprofit_noloss(100, 200);\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "ProfitLoss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp7h825mpg.php:19\nStack trace:\n#0 /tmp/tmp7h825mpg.php(24): test()\n#1 {main}\n  thrown in /tmp/tmp7h825mpg.php on line 19\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        return true;\n    }\n    return false;\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit, No loss\";\n    } elseif ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmplkafftjo.php:18\nStack trace:\n#0 /tmp/tmplkafftjo.php(23): test()\n#1 {main}\n  thrown in /tmp/tmplkafftjo.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    } else {\n        echo \"Profit or loss\";\n    }\n}\n\nnoprofit_noloss(100, 100);\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "No profit and no lossProfit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpajpayvwf.php:17\nStack trace:\n#0 /tmp/tmpajpayvwf.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpajpayvwf.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        return true;\n    }\n    return false;\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    } else {\n        echo \"Profit or Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "Profit or Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpv859e1_2.php:16\nStack trace:\n#0 /tmp/tmpv859e1_2.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpv859e1_2.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        return true;\n    }\n    else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    } else {\n        echo \"Profit or loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpousfa8wn.php:16\nStack trace:\n#0 /tmp/tmpousfa8wn.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpousfa8wn.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n\tif ($actual_cost == $sale_amount) {\n\t\treturn true;\n\t} else {\n\t\treturn false;\n\t}\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    } else {\n        echo \"Profit or loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpousfa8wn.php:16\nStack trace:\n#0 /tmp/tmpousfa8wn.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpousfa8wn.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    }\n    else {\n        echo \"Profit or loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123509,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpdjzgxw2f.php:17\nStack trace:\n#0 /tmp/tmpdjzgxw2f.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpdjzgxw2f.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n\tif($actual_cost == $sale_amount) {\n\t\treturn true;\n\t}\n\telse {\n\t\treturn false;\n\t}\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    }\n    else {\n        echo \"Profit or loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpoudd94_b.php:17\nStack trace:\n#0 /tmp/tmpoudd94_b.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpoudd94_b.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n\tif ($actual_cost == $sale_amount) {\n\t\techo \"No profit and no loss\";\n\t}\n\telse {\n\t\techo \"Profit or loss\";\n\t}\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123509,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmphsdbqcaf.php:17\nStack trace:\n#0 /tmp/tmphsdbqcaf.php(22): test()\n#1 {main}\n  thrown in /tmp/tmphsdbqcaf.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    } else {\n        echo \"Profit or Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "Profit or Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpv859e1_2.php:16\nStack trace:\n#0 /tmp/tmpv859e1_2.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpv859e1_2.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    }\n}\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp2tsj7oa_.php:13\nStack trace:\n#0 /tmp/tmp2tsj7oa_.php(18): test()\n#1 {main}\n  thrown in /tmp/tmp2tsj7oa_.php on line 13\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    } elseif ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123509,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpmj6qq7wm.php:18\nStack trace:\n#0 /tmp/tmpmj6qq7wm.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpmj6qq7wm.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    } elseif ($actual_cost < $sale_amount) {\n        echo \"Profit\";\n    } else {\n        echo \"Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmphbxouuwx.php:18\nStack trace:\n#0 /tmp/tmphbxouuwx.php(23): test()\n#1 {main}\n  thrown in /tmp/tmphbxouuwx.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    } elseif ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nnoprofit_noloss(100, 100);\necho \"<br>\";\nnoprofit_noloss(100, 200);\necho \"<br>\";\nnoprofit_noloss(200, 100);\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "No profit and no loss<br>Profit<br>LossLoss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp94xotmsq.php:23\nStack trace:\n#0 /tmp/tmp94xotmsq.php(28): test()\n#1 {main}\n  thrown in /tmp/tmp94xotmsq.php on line 23\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return \"No Profit No Loss\";\n    } else {\n        return \"Profit or Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123509,
      "stdout": "\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp4ki4bwlh.php:16\nStack trace:\n#0 /tmp/tmp4ki4bwlh.php(21): test()\n#1 {main}\n  thrown in /tmp/tmp4ki4bwlh.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n\tif($actual_cost == $sale_amount) {\n\t\treturn true;\n\t}\n\treturn false;\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    }\n    else if($actual_cost < $sale_amount) {\n        echo \"Profit\";\n    }\n    else {\n        echo \"Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpql_fhmlr.php:20\nStack trace:\n#0 /tmp/tmpql_fhmlr.php(25): test()\n#1 {main}\n  thrown in /tmp/tmpql_fhmlr.php on line 20\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    }\n    else {\n        echo \"Profit or loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmptrb21y6k.php:17\nStack trace:\n#0 /tmp/tmptrb21y6k.php(22): test()\n#1 {main}\n  thrown in /tmp/tmptrb21y6k.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } else {\n        echo \"Profit or loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123509,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxhaaqc47.php:16\nStack trace:\n#0 /tmp/tmpxhaaqc47.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpxhaaqc47.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    } else if ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123509,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmptnre1x9m.php:18\nStack trace:\n#0 /tmp/tmptnre1x9m.php(23): test()\n#1 {main}\n  thrown in /tmp/tmptnre1x9m.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123509,
      "stdout": "\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp_jwvkcw3.php:14\nStack trace:\n#0 /tmp/tmp_jwvkcw3.php(19): test()\n#1 {main}\n  thrown in /tmp/tmp_jwvkcw3.php on line 14\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"There is no profit and no loss\";\n    } else {\n        echo \"There is profit or loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123509,
      "stdout": "There is profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpy4zmbikj.php:16\nStack trace:\n#0 /tmp/tmpy4zmbikj.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpy4zmbikj.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123509,
      "stdout": "\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp_jwvkcw3.php:14\nStack trace:\n#0 /tmp/tmp_jwvkcw3.php(19): test()\n#1 {main}\n  thrown in /tmp/tmp_jwvkcw3.php on line 14\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    } elseif ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpxwx_8k6i.php:18\nStack trace:\n#0 /tmp/tmpxwx_8k6i.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpxwx_8k6i.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    } else {\n        echo \"Profit or loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpousfa8wn.php:16\nStack trace:\n#0 /tmp/tmpousfa8wn.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpousfa8wn.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit, No loss\";\n    } else if ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123509,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpa0nyo_2r.php:18\nStack trace:\n#0 /tmp/tmpa0nyo_2r.php(23): test()\n#1 {main}\n  thrown in /tmp/tmpa0nyo_2r.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n\t$profit = $sale_amount - $actual_cost;\n\tif ($profit == 0) {\n\t\techo \"No profit no loss\";\n\t}\n\telse {\n\t\techo \"Profit or loss\";\n\t}\n}\nnoprofit_noloss(1000, 1000);\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "No profit no lossProfit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp4asj9sj_.php:18\nStack trace:\n#0 /tmp/tmp4asj9sj_.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp4asj9sj_.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    } else {\n        echo \"Profit or loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpousfa8wn.php:16\nStack trace:\n#0 /tmp/tmpousfa8wn.php(21): test()\n#1 {main}\n  thrown in /tmp/tmpousfa8wn.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit no loss\";\n    }\n    else {\n        echo \"Profit or loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmptrb21y6k.php:17\nStack trace:\n#0 /tmp/tmptrb21y6k.php(22): test()\n#1 {main}\n  thrown in /tmp/tmptrb21y6k.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n\tif($actual_cost == $sale_amount) {\n\t\treturn true;\n\t} else {\n\t\treturn false;\n\t}\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n\tif ($actual_cost == $sale_amount) {\n\t\techo \"No profit no loss\";\n\t}\n\telse {\n\t\techo \"Profit or loss\";\n\t}\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Profit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpkrm_mohk.php:17\nStack trace:\n#0 /tmp/tmpkrm_mohk.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpkrm_mohk.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        echo \"No Profit No Loss\";\n    }\n    else {\n        echo \"Profit or Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123509,
      "stdout": "Profit or Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp8ok6o0hz.php:17\nStack trace:\n#0 /tmp/tmp8ok6o0hz.php(22): test()\n#1 {main}\n  thrown in /tmp/tmp8ok6o0hz.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if($actual_cost == $sale_amount) {\n        return true;\n    }\n    return false;\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510446,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n\tif($actual_cost == $sale_amount) {\n\t\techo \"No profit no loss\";\n\t}\n\telse {\n\t\techo \"Profit or loss\";\n\t}\n}\nnoprofit_noloss(1000, 1000);\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "No profit no lossProfit or loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpcdwc8usz.php:17\nStack trace:\n#0 /tmp/tmpcdwc8usz.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpcdwc8usz.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        return true;\n    } else {\n        return false;\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1665510445,
      "stdout": "",
      "stderr": "",
      "exit_code": 0,
      "status": "OK"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit, No loss\";\n    } else {\n        echo \"Profit or Loss\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Profit or Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmps73pajwm.php:16\nStack trace:\n#0 /tmp/tmps73pajwm.php(21): test()\n#1 {main}\n  thrown in /tmp/tmps73pajwm.php on line 16\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n\tif($actual_cost == $sale_amount) {\n\t\techo \"No Profit No Loss\";\n\t}\n\telse {\n\t\techo \"Profit or Loss\";\n\t}\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123510,
      "stdout": "Profit or Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmpmel8uxor.php:17\nStack trace:\n#0 /tmp/tmpmel8uxor.php(22): test()\n#1 {main}\n  thrown in /tmp/tmpmel8uxor.php on line 17\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    },
    {
      "program": "<?php\n// Write a function to check whether the given amount has no profit and no loss\nfunction noprofit_noloss($actual_cost, $sale_amount) {\n    if ($actual_cost == $sale_amount) {\n        echo \"No profit and no loss\";\n    } elseif ($actual_cost > $sale_amount) {\n        echo \"Loss\";\n    } else {\n        echo \"Profit\";\n    }\n}\n\nfunction candidate(...$args) {\n    return noprofit_noloss(...$args);\n}\n\nfunction test(): void {\n    if (candidate(1500, 1200) !== false) { throw new Exception(\"Test failed!\"); }\n    if (candidate(100, 100) !== true) { throw new Exception(\"Test failed!\"); }\n    if (candidate(2000, 5000) !== false) { throw new Exception(\"Test failed!\"); }\n}\n\ntest();",
      "timestamp": 1666123509,
      "stdout": "Loss\nFatal error: Uncaught Exception: Test failed! in /tmp/tmp0qbfdmyo.php:18\nStack trace:\n#0 /tmp/tmp0qbfdmyo.php(23): test()\n#1 {main}\n  thrown in /tmp/tmp0qbfdmyo.php on line 18\n",
      "stderr": "",
      "exit_code": 255,
      "status": "Exception"
    }
  ]
}