code,description,count,gold,examples
IndexError,List index out of range,460, ---- HumanEval_89_encrypt --- completion 7,../error-examples/python-error-examples/IndexError.py
NameError,The name is not defined,2942, ---- HumanEval_127_intersection --- completion 0 ,../error-examples/python-error-examples/NameError.py
TypeError,Type of objects in an operation is inappropriate,123,---- HumanEval_137_compare_one --- completion 1 ----,../error-examples/python-error-examples/TypeError.py
ValueError,A function received an argument of the correct type but an inappropriate value,334,HumanEval_155_even_odd_count --- completion 0,../error-examples/python-error-examples/ValueError.py
NotImplementedError,Raised by Codex generated code,253,HumanEval_20_find_closest_elements --- completion 0,../error-examples/python-error-examples/NotImplementedError.py
IndentationError,Indentation of a line is wrong,32,HumanEval_129_minPath --- completion 27,../error-examples/python-error-examples/IndentationError.py
KeyError,Request key is not present in dictionary,2,HumanEval_19_sort_numbers --- completion 29,../error-examples/python-error-examples/KeyError.py
UnboundLocalError,A local variable is referenced before assignment,1,HumanEval_129_minPath --- completion 31,../error-examples/python-error-examples/UnboundLocalError.py
AttributeError,Requested attribute is not present in the object,5,---- HumanEval_92_any_int --- completion 0 ----,../error-examples/python-error-examples/AttributeError.py
RecursionError,Maximum recursion depth exceeded,86,HumanEval_138_is_equal_to_sum_even --- completion 1,../error-examples/python-error-examples/RecursionError.py
ZeroDivisionError,Division by zero,1,HumanEval_128_prod_signs --- completion 2,../error-examples/python-error-examples/ZeroDivisionError.py
EOFError,EOF when reading a line,1,HumanEval_41_car_race_collision --- completion 1,../error-examples/python-error-examples/EOFError.py
SyntaxError,"Invalid syntax due to un-matched closing brace, bracket, or colon ':'",333, HumanEval_43_pairs_sum_to_zero --- completion 0,../error-examples/python-error-examples/SyntaxError.py
Timeout,Program is running for more than 5 mins,4462,---- HumanEval_100_make_a_pile --- completion 106 ----,../error-examples/python-error-examples/Timeout.py
OK,Program ran fine,19492,,../error-examples/python-error-examples/OK.py
AssertionError,Assertion failed,17104,,../error-examples/python-error-examples/AssertionError.py
